config/routes.rb
AviewWebapp::Application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  apipie

  namespace :api, defaults: { format: :json } do
    api_version(module: 'V1', path: { value: 'v1' }, default: false) do
      namespace :auth do
        resources :att_bc, only: [:create, :index]
      end
    end

    api_version(module: 'V2', path: { value: 'v2' }, default: true) do
      resources :devices, only: [:index, :show] do
        member do
          patch :update_settings
        end
      end
      resources :accounts, only: [:update] do
        member do
          patch :update_password
          patch :update_filter
          patch :clear_filter
          patch :generate_api_token
        end

        resources :devices, only: [:index, :show, :update] do
        end

        resources :notification_subscriptions do
          collection do
            get :search
            get :reset
          end
        end

        resources :notification_profiles do
          member do
            get :subscriptions
          end
        end
      end
      resources :users
      resources :roles
      resources :sites
      resources :passwords, only: [:update]
      resources :organizations do
        member do
          get :abilities
        end
      end
    end

    api_version(module: 'V3', path: { value: 'v3' }, default: false) do
      resources :devices, only: [:update] do
        member do
          patch :update_location
          patch :clear_location
        end

        resources :contacts, only: [:new, :show, :update, :create, :index, :destroy]
        resources :dial_tests, only: [:index]
      end
    end

    api_version(module: 'V4', path: { value: 'v4' }, default: false) do
      resources :devices, only: [:index] do
        collection do
          get :usage
        end
      end
    end
  end

  scope module: :api, defaults: {format: :json} do
    namespace :device_configurations do
      resources :v2, only: [:show]
    end

    namespace :certificates do
      resources :v2, only: [:create]
      post '/', controller: 'v2', action: :create
    end
  end

  post "/pdns/lookup", to: "power_dns_backend#lookup"
  post "/pdns/getDomainMetadata", to: proc { [404, {}, ['']] }
  post "/pdns/calculateSOASerial", to: proc { [404, {}, ['']] }

  resource :dashboard, only: :show do
    collection do
      get 'device_table'
    end
  end

  resource :highcharts, only: [] do
    collection do
      get 'cellular_utilization'
      get 'connectivity_status_chart'
      get 'deployed_status_chart'
      get 'ids_alerts_histogram'
      get 'network_type_chart'
      get 'signal_strength_chart'
      get 'intelliflow_app_usage'
      get 'intelliflow_app_usage_over_time'
      get 'wan_utilization'
    end
  end

  root :to => 'dashboards#show'

  devise_for :users
  resources :users do
    resources :permissions

    collection do
      resource :activation, controller: :activations, only: [:new, :create]
    end
  end

  resources :account, :except => :show do
    patch :update, :on => :collection
    patch :change, :on => :collection
    get   :change, :on => :collection
    get   :change_password, :on => :collection
    patch :update_password, :on => :collection
    get   :api, :on => :collection
    patch :generate_api_token, :on => :collection
  end

  resources :searches, only: [:index, :new]

  resources :notifications do
    get :since, :on => :collection
  end

  post 'data_tables/devices/(:data_table_class)/(:reference_id)', to: 'data_tables#devices', as: :devices_data_tables
  post 'data_tables/events/(:mac)', to: 'data_tables#events', as: :events_data_tables
  # TODO: Get rid of index route and action, used by reports
  resources :data_tables, only: [] do
    collection do
      post :searches
      post :sites
      post :users
      post :notifications
      post :intelliflow_client_usage
      post :groups
      post :group_devices
    end
  end

  resources :devices, except: :create do
    collection do
      get :vpn_gateway
      get :wifi
      get :legacy_cellular
      get :cellular
      get :dial_to_ip
      get :remote_manager
      get :ucpe
      get :to_csv

      post :with_selected
      post :vpn_gateway
      post :wifi
      post :legacy_cellular
      post :cellular
      post :dial_to_ip
      post :remote_manager
      post :ucpe
    end

    member do
      get :terminal
      get :toggle_deployment
      get :replace
      get :events
      get :remove_contact
      get :commands_list
      get :remote
      get :organization_configurations
      get :move_to_organization

      post :replace_with
      post :add_contact

      patch :remote
      patch :save_configuration
    end

    resources :modems, only: :destroy

    resources :charts do
      collection do
        get :signal
        get :network
      end
    end

    resources :device_associations do
      collection do
        get :table
      end
    end

    get "/events/since" => "devices#events_since"

    namespace :configuration do
      resource :network, only: [:show, :update]
      resource :internet_routes, only: [:show, :create, :update, :destroy] do
        delete :destroy_all
      end
      resource :cascaded_networks, only: [:show, :create, :update, :destroy] do
        delete :destroy_all
      end
    end

    resources :ids_alerts, only: :index
  end

  resources :tunnel_servers, only: [:index, :show] do
    member do
      get :ip_addresses
    end
  end

  resources :configurations

  get '/configurations/:id/device_config', to: 'legacy_configurations#device_config'

  constraints subdomain: "#{Settings.subdomains.configurations}" do
    get '/:id', to: 'legacy_configurations#device_config'
  end

  resources :legacy_configurations do
    collection do
      get :inherited_values
      get :available_parents
      get :organization_configurations
      get :parent_configuration
      get :exists_for_organization
      get :cellular
    end

    member do
      post  :copy
      get   :device_config
    end
  end

  resources :reports do
    member do
      post :export
    end

    collection do
      get :availability
      get :cellular_network_type
      get :cellular_utilization
      get :cellular_signal_strength
      get :vig
      get :finished_generating
    end
  end

  resources :chart_data do
    get :device, :on => :collection
  end

  resources :sites do
    get :to_csv, :on => :collection

    collection do
      get :search
    end
  end

  resources :organizations do
    member do
      get   :edit_logo
      patch :update_logo
      get   :edit_footer
      patch :update_footer
      patch :update_device_settings
      get :actions_menu
    end

    collection do
      post  :move_devices_to
      get :search
    end

    resources :roles do
      get :abilities
    end

    resources :permissions
    resources :data_plans do
      collection do
        post :move_devices_to
        get :exists_for_organization
      end
    end


  end

  resources :maps do
    get :pins, :on => :collection
    get :alert_pins, :on => :collection
  end

  resources :events do
    get :new_since, :on => :collection
    get :since, :on => :collection
  end

  resources :device_configurations, except: [:index] do
    collection do
      get '/v2/:mac', to: 'device_configurations#device'
      get :dial_to_ip
      get :remote_manager
      get :cellular
      get :ucpe
      get :exists_for_organization
    end
    member do
      get   :edit_linked_devices
      patch :update_linked_devices
      post  :copy
    end
  end

  resources :device_firmwares, only: [] do
    member do
      get :schema_file
    end
  end

  get '/admin', :to => 'admin#index'

  get '/vvig_pnc', :to => 'vvig_pnc#index'

  get '/vvig_pnc/data', :to => 'vvig_pnc#get_data'

  namespace :admin do
    get :server_log

    get :device_statistics

    resources :dns

    resources :imports do
      collection do
        get     :template
        delete  :destroy_all
      end

      member do
        get :objects
      end
    end

    resources :certificates, only: [:index, :destroy] do
      member do
        patch :approve
      end
    end

    resources :customer_services, except: [:show]

    resources :settings, only: [] do
      collection do
        patch :update
      end
    end
  end

  resources :device_models, only: [:index] do
    resources :device_firmwares, only: [:index]

    member do
      get :firmware_select
    end
  end

  resources :groups do
    collection do
      post :destroy_multiple
    end

    member do
      get :device_search
      post :add_devices
      post :remove_devices
      get :edit_firmware
      post :update_firmware
      get :group_widgets
      get :configuration
    end
  end

  namespace :services, defaults: { format: :json } do
    scope :configurations do
      get   'device/:device_id', to: 'configurations#device'
      patch 'device/:device_id', to: 'configurations#update_device'
      get   'schemas/:model/ui', to: 'configurations/schemas#ui'
    end
  end

  post "/feedback" => "feedback#create"

  get "/cellular_locations" => "cellular_locations#show"

  get "/401" => "errors#unauthorized"
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  get '*unmatched_route', via: :all, to: 'errors#not_found'
end

app/models/group.rb
class Group < ActiveRecord::Base
  include Searchable

  belongs_to :organization
  belongs_to :device_model
  belongs_to :firmware, class_name: 'DeviceFirmware'
  has_many :devices, dependent: :nullify
  has_one :category, through: :device_model

  validates :name, presence: true, length: { minimum: 3, maximum: 255 },
            uniqueness: { scope: :organization_id, case_sensitive: false }
  validates :organization_id, presence: true
  validates :device_model_id, presence: true
  validates :firmware_id, presence: true

  has_search_scope :with_name_search, ->(search) { where('groups.name LIKE ?', "%#{search}%") }
  has_search_scope :with_categories, ->(categories) { joins(:device_model).where(device_models: { category_id: categories }) }
  has_search_scope :with_models, ->(models) { where(device_model_id: models) }
  has_search_scope :with_firmware_search, ->(search) {
    joins(:firmware).where("device_firmwares.version LIKE ?", "%#{search}%")
  }
  has_search_scope :sort_by_name, ->(direction) { order("name #{sort_direction direction}") }
  has_search_scope :sort_by_device_categories_name, ->(direction) {
    joins(:category).order("device_categories.name #{sort_direction direction}")
  }
  has_search_scope :sort_by_device_models_name, ->(direction) {
    joins(:device_model).order("device_models.name #{sort_direction direction}")
  }
  has_search_scope :sort_by_firmware_name, ->(direction) {
    joins(:firmware).order("device_firmwares.version #{sort_direction direction}")
  }

  delegate :category_name, to: :device_model, prefix: false, allow_nil: true
  delegate :name,          to: :device_model, prefix: true, allow_nil: true
  delegate :device_firmwares, to: :device_model

  def title
    "#{category_name} #{device_model_name} #{name}"
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  before_filter :base_breadcrumbs
  before_action :set_group, except: [:index, :new, :create, :destroy_multiple]

  # GET /groups
  def index
    authorize Group, :modify?
    @presenter = GroupsPresenter.new(view_context)
  end

  # GET /groups/new.js
  def new
    @group = Group.new
    authorize Group, :modify?

    respond_to do |format|
      format.js {}
    end
  end

  # POST /groups
  # POST /groups.json
  # POST /groups.js
  def create
    @group = Group.new(group_params)
    authorize @group, :modify?

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
        format.js   {}
      else
        format.html { redirect_to groups_path, error: 'Group was not created.' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
        format.js   { render partial: 'modal_errors' }
      end
    end
  end

  # GET /groups/1
  def show
    @presenter = GroupDevicesPresenter.new(view_context)
    add_breadcrumb @group.name
  end

  # GET /groups/1/group_stats.html
  def group_widgets
    @presenter = GroupDevicesPresenter.new(view_context)
    render partial: 'group_widgets'
  end

  # GET /groups/1/configuration
  def configuration
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
      format.js   {}
    end
  end

  # GET /groups/1/device_search.json?query=002704
  def device_search
    # Only search for devices with model
    @devices = @group.organization.devices.not_in_group(@group.id)
                     .select(:id, :mac)
                     .where('devices.mac like ?', "%#{params[:query]}%")
                     .where(model_id: @group.device_model_id)
                     .limit(10)

    respond_to do |format|
      format.json { render json: { results: @devices }, root: false }
    end
  end

  def add_devices
    @devices = @group.organization.devices.where(id: params[:device_ids],
                                           model_id: @group.device_model_id)
    @devices.update_all(group_id: @group.id)
  end

  def remove_devices
    @devices = @group.devices.where(id: params[:device_ids])
    @count = @devices.count
    @devices.update_all(group_id: nil)
  end

  # GET /groups/1/edit_firmware.js
  def edit_firmware
    include_beta = ::Pundit.policy(current_user, DeviceFirmware).assign_non_production?
    @firmwares = @group.firmware.self_and_parents(include_beta)
  end

  # POST /groups/1/update_firmware.js
  def update_firmware
    @group.assign_attributes(group_params)

    respond_to do |format|
      if @group.save
        format.js {}
      else
        format.js { render partial: 'modal_errors' }
      end
    end
  end

  # POST /groups/destroy_multiple
  def destroy_multiple
    authorize Group, :modify?

    @groups = current_user.groups.where(id: params[:group_ids])
    @group_names = @groups.map(&:name)
    @groups.destroy_all

    respond_to do |format|
      format.html { redirect_to groups_path, notice: 'Groups were successfully destroyed.' }
      format.json { head :no_content }
      format.js   {}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = current_user.groups.find(params[:id])
    authorize @group, :modify?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params[:group].permit(:name, :organization_id, :device_model_id, :firmware_id)
  end

  def base_breadcrumbs
    add_breadcrumb "Home", "/"
    add_breadcrumb "Groups", '/groups'
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_errors.js.erb
var alerts = ''

<% @group.errors.full_messages.each do |message| %>
    alerts += "<%= j alert_error message: message %>";
<% end %>

$("<%= element.html_safe %>").prepend(alerts);

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/groups/_group_widgets.html.erb
<div class="col-md-2">
  <div class="widget text-center no-margins">
    <div class="m-b-md">
      <h1 class="m-xs text-info"><%= @presenter.devices_online %></h1>
      <h3 class="font-bold no-margins">
        Online
      </h3>
    </div>
  </div>
</div>

<div class="col-md-2">
  <div class="widget text-center no-margins">
    <div class="m-b-md">
      <h1 class="m-xs text-danger"><%= @presenter.devices_offline %></h1>
      <h3 class="font-bold no-margins">
        Offline
      </h3>
    </div>
  </div>
</div>

<div class="col-md-2">
  <div class="widget text-center no-margins">
    <div class="m-b-md">
      <h1 class="m-xs"><%= @presenter.devices_deployed %></h1>
      <h3 class="font-bold no-margins">
        Deployed
      </h3>
    </div>
  </div>
</div>

<div class="col-md-2">
  <div class="widget text-center no-margins">
    <div class="m-b-md">
      <h1 class="m-xs"><%= @presenter.devices_undeployed %></h1>
      <h3 class="font-bold no-margins">
        Undeployed
      </h3>
    </div>
  </div>
</div>

<div class="col-md-2">
  <div class="widget text-center no-margins">
    <div class="m-b-md">
      <h1 class="m-xs"><%= @presenter.devices_activated %></h1>
      <h3 class="font-bold no-margins">
        Activated
      </h3>
    </div>
  </div>
</div>

<div class="col-md-2">
  <div class="widget text-center no-margins">
    <div class="m-b-md">
      <h1 class="m-xs text-primary"><%= @presenter.devices_total %></h1>
      <h3 class="font-bold no-margins">
        Total
      </h3>
    </div>
  </div>
</div>

app/views/groups/_modal_errors.js.erb
$('.modal-body').find('.alert').remove();

var alerts = ''

<% @group.errors.full_messages.each do |message| %>
  alerts += "<%= j alert_error message: message %>";
<% end %>

$(".modal-body").prepend(alerts);

app/views/groups/add_devices.js.erb
$(".device-ids-select").select2("val", "");
$('#add-group-devices-modal').modal('hide');

refreshGroupWidgets();

$('#group-devices-table').DataTable().ajax.reload(function() {
  var deviceCount = '<%= @devices.count %>';
  var pluralizedDevice = '<%= "device".pluralize(@devices.count) %>';
  var groupName = '<%= @group.name %>';
  var message = 'Successfully added ' + deviceCount + ' ' + pluralizedDevice + ' to group "' + groupName + '".';
  var title = pluralizedDevice.capitalize() + ' Added';

  toastr.success(message, title);
});

app/views/groups/create.js.erb
$('#new-group-modal').modal('hide');

$('#groups-table').DataTable().ajax.reload(function() {
  toastr.success('Successfully created group "<%= @group.name %>".', 'Group Created');
  flashElement($('#group_row_<%= @group.id %>'));
});

app/views/groups/edit_firmware.js.erb
var modal = "<%= j render(partial: 'groups/modals/edit_firmware') %>";

$('#modals-container').html(modal)
$('#edit-group-firmware-modal .select2').select2({ theme: 'bootstrap' })
$('#edit-group-firmware-modal').modal({backdrop: 'static'});

app/views/groups/index.html.erb
<%= render 'shared/page_header_vs', locals: { title: @presenter.title } %>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <div class="groups-toolbar">
            <%= link_to(new_group_path(format: :js), class: 'btn btn-link single-button-remote', remote: true) do %>
              <i class="fa fa-plus"></i> Add
            <% end %>

            <%= link_to("#", class: 'btn btn-link single-select-button disabled', id: 'delete-groups', 'data-toggle' => 'modal', 'data-target' => '#destroy-groups-modal') do %>
              <i class="fa fa-times"></i> Delete
            <% end %>

            <div class="btn-group">
              <a data-toggle="dropdown" id="group-configuration" class="btn btn-link dropdown-toggle disabled">
                <i class="fa fa-wrench"></i> Configuration <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><a href="#" id="edit-group-configuration"><i class="fa fa-pencil"></i> Edit</a></li>
                <li><a href="#"><i class="fa fa-th-list"></i> Summary</a></li>
                <li><a href="#"><i class="fa fa-times-circle"></i> Clear</a></li>
                <li><a href="#"><i class="fa fa-copy"></i> Copy To ...</a></li>
              </ul>
            </div>

            <%= link_to("#", class: 'btn btn-link single-select-button single-button-remote disabled', id: 'edit-group-firmware', remote: true) do %>
              <i class="fa fa-codepen"></i> Firmware
            <% end %>

            <a id="group-settings" class="btn btn-link disabled">
              <i class="fa fa-sliders"></i> Settings
            </a>

            <a href="#" title="Refresh" id="refresh-data-table" class="btn btn-link pull-right">
              <i class="fa fa-refresh"></i>
            </a>
          </div>

          <div class="clear"></div>
        </div>

        <div class="ibox-content">
          <div class="table-responsive vs-target-wrapper" data-no-vs-spinner="true" data-facets="<%= @presenter.facets.to_json %>">
            <table class="table table-striped table-bordered table-hover vs-table dataTable datatable-v2" id="groups-table">
              <thead>
                <tr>
                  <%= render 'shared/table_labels' %>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td colspan="<%= @presenter.columns.count %>">
                    <center><%= image_tag('ajax-loader.gif') %></center>
                  </td>
                </tr>
              </tbody>
            </table>
            <div class="clear"></div>
            <div id="table-ender"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'groups/modals/destroy_multiple' %>

<script type="text/javascript">
  var dataTableURI = '<%= groups_data_tables_path %>';

  function initDataTable(columns, table) {
    table.DataTable(makeDataTableV2(columns, table, dataTableURI));
  }

  function selectedGroupID() {
    return $('.group-select:checked').val();
  }

  function enableDeleteGroupsButton() {
    $('#delete-groups').removeClass('disabled');
  }

  function disableDeleteGroupsButton() {
    $('#delete-groups').addClass('disabled');
  }

  function enableConfigurationButton() {
    $('#group-configuration').removeClass('disabled');
  }

  function disableConfigurationButton() {
    $('#group-configuration').addClass('disabled');
  }

  function enableFirmwareButton() {
    $('#edit-group-firmware').removeClass('disabled');
  }

  function disableFirmwareButton() {
    $('#edit-group-firmware').addClass('disabled');
  }

  function enableSettingsButton() {
    $('#group-settings').removeClass('disabled');
  }

  function disableSettingsButton() {
    $('#group-settings').addClass('disabled');
  }

  function enableSingleSelectButtons() {
    enableConfigurationButton();
    enableFirmwareButton();
    enableSettingsButton();
  }

  function disableSingleSelectButtons() {
    disableConfigurationButton();
    disableFirmwareButton();
    disableSettingsButton();
  }

  function disableAllSelectDependentButtons() {
    disableDeleteGroupsButton();
    disableSingleSelectButtons();
  }

  function groupCount() {
    return $('.group-select').length
  }

  function groupSelectedCount() {
    return $('.group-select:checked').length
  }

  function disableGlobalCheckbox() {
    $('.group-select-all').prop('checked', false);
  }

  function enableGlobalCheckbox() {
    $('.group-select-all').prop('checked', true);
  }

  $(document).ready(function () {

    // Toggle toolbar buttons when groups are checked / unchecked. We use
    // livequery here to attach to checkboxes injected into the DOM when new
    // groups are created.
    $('.group-select').livequery(function() {
      $(this).on('change', function() {
        var selectedCount = groupSelectedCount();
        var count = groupCount();

        if (selectedCount) {
          // Some buttons are toggled only if a single row is checked
          if (selectedCount > 1) {
            disableSingleSelectButtons();
          } else {
            enableSingleSelectButtons();
          }

          enableDeleteGroupsButton();

          // Toggle the global checkbox
          if (selectedCount != count) {
            disableGlobalCheckbox();
          } else {
            enableGlobalCheckbox();
          }
        } else {
          disableAllSelectDependentButtons();
        }
      });
    });

    // Global group checkbox toggle
    $('.group-select-all').livequery(function() {
      $(this).on('change', function() {
        var groupSelect = $('.group-select');

        if ($('.group-select-all:checked').length) {
          groupSelect.prop('checked', true);
        } else {
          groupSelect.prop('checked', false);
        }

        // Ensure toolbar buttons are toggled correctly
        groupSelect.trigger('change');
      });
    });

    $('#edit-group-configuration').on('click', function(e) {
      window.location.href = '/groups/' + selectedGroupID() + '/configuration';
      e.preventDefault();
    });

    $("#edit-group-firmware").on('click', function(e) {
      e.originalEvent.currentTarget.href = '/groups/' + selectedGroupID() + '/edit_firmware.js';
    });

    $('#groups-table').on('draw.dt', function() {
      disableSingleSelectButtons();
      disableGlobalCheckbox();
    });

  });
</script>

app/views/groups/show.html.erb
<%= render 'shared/page_header', locals: { title: @group.title, skip_translate: true } %>

<div class="wrapper wrapper-content">
  <div class="row" id="group-widgets-container">
    <%= render partial: 'group_widgets' %>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <div class="groups-toolbar">
            <%= link_to('#', class: 'btn btn-link', id: 'add-devices', 'data-toggle' => 'modal', 'data-target' => '#add-group-devices-modal') do %>
              <i class="fa fa-plus"></i>&nbsp;Add Devices
            <% end %>

            <%= link_to("#", class: 'btn btn-link disabled', id: 'remove-devices', 'data-toggle' => 'modal', 'data-target' => '#remove-group-devices-modal') do %>
              <i class="fa fa-times"></i> Remove Devices
            <% end %>

            <div class="btn-group">
              <a data-toggle="dropdown" id="group-configuration" class="btn btn-link dropdown-toggle">
                <i class="fa fa-wrench"></i> Configuration <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to(configuration_group_path(@group)) do %>
                    <i class="fa fa-pencil"></i> Edit
                  <% end %>
                </li>
                <li><a href="#"><i class="fa fa-th-list"></i> Summary</a></li>
                <li><a href="#"><i class="fa fa-times-circle"></i> Clear</a></li>
                <li><a href="#"><i class="fa fa-copy"></i> Copy To ...</a></li>
              </ul>
            </div>

            <%= link_to(edit_firmware_group_path(@group), class: 'btn btn-link single-button-remote', id: 'edit-group-firmware', remote: true) do %>
              <i class="fa fa-codepen"></i> Firmware
            <% end %>

            <a id="group-settings" class="btn btn-link">
              <i class="fa fa-sliders"></i> Settings
            </a>

            <a href="#" title="Refresh" id="refresh-data-table" class="btn btn-link pull-right">
              <i class="fa fa-refresh"></i>
            </a>
          </div>

          <div class="clear"></div>
        </div>

        <div class="ibox-content">
          <div class="table-responsive vs-target-wrapper" data-facets="<%= @presenter.facets.to_json %>">
            <table class="table table-striped table-bordered table-hover vs-table dataTable datatable-v2" id="group-devices-table">
              <thead>
                <tr>
                  <%= render 'shared/table_labels' %>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td colspan="<%= @presenter.columns.count %>">
                    <center><%= image_tag('ajax-loader.gif') %></center>
                  </td>
                </tr>
              </tbody>
            </table>
            <div class="clear"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'groups/modals/add_devices' %>
<%= render partial: 'groups/modals/remove_devices' %>

<% content_for :header_javascript_block  do %>
  <script type="text/javascript">

    function enableRemoveDevicesButton() {
      $('#remove-devices').removeClass('disabled');
    }

    function disableRemoveDevicesButton() {
      $('#remove-devices').addClass('disabled');
    }

    var dataTableURI = '<%= group_devices_data_tables_path(group_id: @group.id) %>';

    function initDataTable(columns, table) {
      table.DataTable(makeDataTableV2(columns, table, dataTableURI));
    }

    function refreshGroupWidgets() {
      $.ajax({
        url: '<%= group_widgets_group_path(@group) %>',
        dataType: 'html',
        success: function(data) {
          $("#group-widgets-container").html(data);
        }
      });
    }

    $(document).ready(function () {
      $('.device-select').livequery(function() {
        $(this).on('change', function() {
          if ($('.device-select:checked').length) {
            enableRemoveDevicesButton();

            // Enable/disable the global checkbox
            if ($('.device-select:checked').length != $('.device-select').length) {
              $('.device-select-all').prop('checked', false);
            } else {
              $('.device-select-all').prop('checked', true);
            }
          } else {
            disableRemoveDevicesButton();
          }
        });
      });

      $('.device-select-all').livequery(function() {
        $(this).on('change', function() {
          if ($('.device-select-all:checked').length) {
            $('.device-select').prop('checked', true);
            enableRemoveDevicesButton();
          } else {
            $('.device-select').prop('checked', false);
            disableRemoveDevicesButton();
          }
        });
      });
    });
  </script>
<% end %>