config/routes.rb
AviewWebapp::Application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  apipie

  namespace :api, defaults: { format: :json } do
    api_version(module: 'V1', path: { value: 'v1' }, default: false) do
      namespace :auth do
        resources :att_bc, only: [:create, :index]
      end
    end

    api_version(module: 'V2', path: { value: 'v2' }, default: true) do
      resources :devices, only: [:index, :show] do
        member do
          patch :update_settings
        end
      end
      resources :accounts, only: [:update] do
        member do
          patch :update_password
          patch :update_filter
          patch :clear_filter
          patch :generate_api_token
        end

        resources :devices, only: [:index, :show, :update] do
        end

        resources :notification_subscriptions do
          collection do
            get :search
            get :reset
          end
        end

        resources :notification_profiles do
          member do
            get :subscriptions
          end
        end
      end
      resources :users
      resources :roles
      resources :sites
      resources :passwords, only: [:update]
      resources :organizations do
        member do
          get :abilities
        end
      end
    end

    api_version(module: 'V3', path: { value: 'v3' }, default: false) do
      resources :devices, only: [:update] do
        member do
          patch :update_location
          patch :clear_location
        end

        resources :contacts, only: [:new, :show, :update, :create, :index, :destroy]
        resources :dial_tests, only: [:index]
      end
    end

    api_version(module: 'V4', path: { value: 'v4' }, default: false) do
      resources :devices, only: [:index] do
        collection do
          get :usage
        end
      end
    end
  end

  scope module: :api, defaults: {format: :json} do
    namespace :device_configurations do
      resources :v2, only: [:show]
    end

    namespace :certificates do
      resources :v2, only: [:create]
      post '/', controller: 'v2', action: :create
    end
  end

  post "/pdns/lookup", to: "power_dns_backend#lookup"
  post "/pdns/getDomainMetadata", to: proc { [404, {}, ['']] }
  post "/pdns/calculateSOASerial", to: proc { [404, {}, ['']] }

  resource :dashboard, only: :show do
    collection do
      get 'device_table'
    end
  end

  resource :highcharts, only: [] do
    collection do
      get 'cellular_utilization'
      get 'connectivity_status_chart'
      get 'deployed_status_chart'
      get 'ids_alerts_histogram'
      get 'network_type_chart'
      get 'signal_strength_chart'
      get 'intelliflow_app_usage'
      get 'intelliflow_app_usage_over_time'
      get 'wan_utilization'
    end
  end

  root :to => 'dashboards#show'

  devise_for :users
  resources :users do
    resources :permissions

    collection do
      resource :activation, controller: :activations, only: [:new, :create]
    end
  end

  resources :account, :except => :show do
    patch :update, :on => :collection
    patch :change, :on => :collection
    get   :change, :on => :collection
    get   :change_password, :on => :collection
    patch :update_password, :on => :collection
    get   :api, :on => :collection
    patch :generate_api_token, :on => :collection
  end

  resources :searches, only: [:index, :new]

  resources :notifications do
    get :since, :on => :collection
  end

  post 'data_tables/devices/(:data_table_class)/(:reference_id)', to: 'data_tables#devices', as: :devices_data_tables
  post 'data_tables/events/(:mac)', to: 'data_tables#events', as: :events_data_tables
  # TODO: Get rid of index route and action, used by reports
  resources :data_tables, only: [] do
    collection do
      post :searches
      post :sites
      post :users
      post :notifications
      post :intelliflow_client_usage
      post :groups
      post :group_devices
    end
  end

  resources :devices, except: :create do
    collection do
      get :vpn_gateway
      get :wifi
      get :legacy_cellular
      get :cellular
      get :dial_to_ip
      get :remote_manager
      get :ucpe
      get :to_csv

      post :with_selected
      post :vpn_gateway
      post :wifi
      post :legacy_cellular
      post :cellular
      post :dial_to_ip
      post :remote_manager
      post :ucpe
    end

    member do
      get :terminal
      get :toggle_deployment
      get :replace
      get :events
      get :remove_contact
      get :commands_list
      get :remote
      get :organization_configurations
      get :move_to_organization

      post :replace_with
      post :add_contact

      patch :remote
      patch :save_configuration
    end

    resources :modems, only: :destroy

    resources :charts do
      collection do
        get :signal
        get :network
      end
    end

    resources :device_associations do
      collection do
        get :table
      end
    end

    get "/events/since" => "devices#events_since"

    namespace :configuration do
      resource :network, only: [:show, :update]
      resource :internet_routes, only: [:show, :create, :update, :destroy] do
        delete :destroy_all
      end
      resource :cascaded_networks, only: [:show, :create, :update, :destroy] do
        delete :destroy_all
      end
    end

    resources :ids_alerts, only: :index
  end

  resources :tunnel_servers, only: [:index, :show] do
    member do
      get :ip_addresses
    end
  end

  resources :configurations

  get '/configurations/:id/device_config', to: 'legacy_configurations#device_config'

  constraints subdomain: "#{Settings.subdomains.configurations}" do
    get '/:id', to: 'legacy_configurations#device_config'
  end

  resources :legacy_configurations do
    collection do
      get :inherited_values
      get :available_parents
      get :organization_configurations
      get :parent_configuration
      get :exists_for_organization
      get :cellular
    end

    member do
      post  :copy
      get   :device_config
    end
  end

  resources :reports do
    member do
      post :export
    end

    collection do
      get :availability
      get :cellular_network_type
      get :cellular_utilization
      get :cellular_signal_strength
      get :vig
      get :finished_generating
    end
  end

  resources :chart_data do
    get :device, :on => :collection
  end

  resources :sites do
    get :to_csv, :on => :collection

    collection do
      get :search
    end
  end

  resources :organizations do
    member do
      get   :edit_logo
      patch :update_logo
      get   :edit_footer
      patch :update_footer
      patch :update_device_settings
      get :actions_menu
    end

    collection do
      post  :move_devices_to
      get :search
    end

    resources :roles do
      get :abilities
    end

    resources :permissions
    resources :data_plans do
      collection do
        post :move_devices_to
        get :exists_for_organization
      end
    end


  end

  resources :maps do
    get :pins, :on => :collection
    get :alert_pins, :on => :collection
  end

  resources :events do
    get :new_since, :on => :collection
    get :since, :on => :collection
  end

  resources :device_configurations, except: [:index] do
    collection do
      get '/v2/:mac', to: 'device_configurations#device'
      get :dial_to_ip
      get :remote_manager
      get :cellular
      get :ucpe
      get :exists_for_organization
    end
    member do
      get   :edit_linked_devices
      patch :update_linked_devices
      post  :copy
    end
  end

  resources :device_firmwares, only: [] do
    member do
      get :schema_file
    end
  end

  get '/admin', :to => 'admin#index'

  get '/vvig_pnc', :to => 'vvig_pnc#index'

  get '/vvig_pnc/data', :to => 'vvig_pnc#get_data'

  namespace :admin do
    get :server_log

    get :device_statistics

    resources :dns

    resources :imports do
      collection do
        get     :template
        delete  :destroy_all
      end

      member do
        get :objects
      end
    end

    resources :certificates, only: [:index, :destroy] do
      member do
        patch :approve
      end
    end

    resources :customer_services, except: [:show]

    resources :settings, only: [] do
      collection do
        patch :update
      end
    end
  end

  resources :device_models, only: [:index] do
    resources :device_firmwares, only: [:index]

    member do
      get :firmware_select
    end
  end

  resources :groups do
    collection do
      post :destroy_multiple
    end

    member do
      get :device_search
      post :add_devices
      post :remove_devices
      get :edit_firmware
      post :update_firmware
      get :group_widgets
      get :configuration
    end
  end

  namespace :services, defaults: { format: :json } do
    scope :configurations do
      get   'device/:device_id', to: 'configurations#device'
      patch 'device/:device_id', to: 'configurations#update_device'
      get   'schemas/:model/ui', to: 'configurations/schemas#ui'
    end
  end

  post "/feedback" => "feedback#create"

  get "/cellular_locations" => "cellular_locations#show"

  get "/401" => "errors#unauthorized"
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  get '*unmatched_route', via: :all, to: 'errors#not_found'
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_device
  before_filter :base_breadcrumbs

  # Availability
  def index
    @box_title = "Availability"
    add_breadcrumb @box_title, device_charts_path(@device)
    params[:range] = 'last_week' if params[:range].nil?
    @chart_type = "availability"
  end

  def signal
    @box_title = "Signal Strength"
    add_breadcrumb @box_title, signal_device_charts_path(@device)
    params[:range] = 'last_week' if params[:range].nil?
    @chart_type = "signal_strength"
    render "index"
  end

  def network
    @box_title = "Network"
    add_breadcrumb @box_title, network_device_charts_path(@device)
    params[:range] = 'last_week' if params[:range].nil?
    @chart_type = "network"
    render "index"
  end

  def get_device
    @device = current_user.devices.find_by(mac: params[:device_id])
    redirect_to devices_path and return if @device.nil?
  end

  protected

  def base_breadcrumbs
    add_breadcrumb "Home", "/"
    add_breadcrumb "Devices", devices_path
    add_breadcrumb @device.mac, device_path(@device)
    add_breadcrumb "Analytics", device_charts_path(@device)
  end

end

app/views/shared/charts/_cellular_utilization_chart.html.erb
<% content_for :header_javascript_block  do %>
  <script type="text/javascript">
    $(document).on('tabShown', '#cellular_details', function() {
      if ($('.chart.cellular-utilization').length == 0) { initCharts() }
      else { setActiveChart(); }

      function initCharts() {
        updateCarrierCharts();
        listenForRangeChange();
      }

      function updateCarrierCharts(range) {
        range  = range || '<%= Measurement::Base::DEFAULT_RANGE %>';
        showLoading();

        var jqxhr = getCarrierChartData(range);
        jqxhr.done( function() {
          var response = jqxhr.responseJSON;
          removeOldCharts();
          if ( responseHasData(response) ) { drawCarrierCharts(response) }
          else { renderNoData() }
          updateCarrierSelector();
          setActiveChart();
        });
      }

      function showLoading(){
        var chartElements = $('.chart.cellular-utilization');
        if ( chartElements.length > 0 ) {chartElements.highcharts().hideNoData(); chartElements.highcharts().showLoading();}
      }

      function getCarrierChartData(range) { return $.getJSON(getURI(range)) }

      function getURI(range) {
        var current_device = "<%= params[:id].to_s.upcase %>";
        var uri = "<%= cellular_utilization_highcharts_path %>";
        uri += current_device ? "?id=" + current_device : '';
        uri += range ? "&range=" + range : '';
        return uri;
      }

      function removeOldCharts() { $('.chart.cellular-utilization').remove() }

      function responseHasData(response) { return response.series_by_carrier.length > 0 }

      function drawCarrierCharts(response) {
        $('#carrier-charts').removeClass('hidden');
        $.each(response.series_by_carrier, function (i,carrier) { drawCarrierChart(carrier) });
      }

      function drawCarrierChart(carrier) {
        $('.chart-container.cellular-utilization').append("<div class='chart cellular-utilization hidden' data-carrier='" + carrier.carrier_name + "'\></div>");
        drawHighChart({
          options: cellularUtilizationChartOptions(carrier),
          target: $(carrierChartElementSelector(carrier.carrier_name)),
          type: 'areaspline'
        });
      }

      function updateCarrierSelector() {
        var chartElements = $('.chart.cellular-utilization');
        if ( chartElements.length > 1 ) {
          if ( !carrierSelectorPresent() ) { drawCarrierSelector() }
          updateCarrierSelectorOptions(chartElements);
          listenForCarrierChange();
        }
        else { $('#carrier-select').closest('.form-group').remove() }
      }

      function carrierSelectorPresent() { return $('#carrier-select').length > 0 }

      function drawCarrierSelector() {
        $('#carrier-charts .form').prepend("<%= j render partial: 'shared/charts/components/carrier_select' %>");
      }

      function updateCarrierSelectorOptions(chartElements) {
        $('#carrier-select option').remove();
        $.each(chartElements, function(i, chartElement) { addCarrierSelectorOption($(chartElement).data('carrier')) });
      }

      function addCarrierSelectorOption(carrierName) {
        $('#carrier-select').append("<option " + "value=\"" + carrierChartElementSelector(carrierName) + "\"" + ">" + carrierName + "</option>");
      }

      function carrierChartElementSelector(carrierName) { return ".chart[data-carrier='" + carrierName + "']" }

      function listenForCarrierChange() {
        $('#carrier-select').change(function() {
          showSelectedChart();
        });
      }

      function showSelectedChart() {
        var target = $('#carrier-select').val();
        $('.chart.cellular-utilization').addClass('hidden');
        showAndReflow(target);
      }

      function showAndReflow(target) {
        $(target).removeClass('hidden');
        $(target).highcharts().reflow()
      }

      function renderNoData(){
        $('.chart-container.cellular-utilization').append("<div class='chart cellular-utilization cellular-utilization-chart-no-data'></div>");
        var target = $(".cellular-utilization-chart-no-data");
        drawHighChart({
          options: cellularUtilizationChartOptions(),
          target: target,
          type: 'areaspline'
        });
      }

      function setActiveChart() {
        if ( carrierSelectorPresent() ) { showSelectedChart() }
        else { showAndReflow('.chart.cellular-utilization') }
      }

      function listenForRangeChange() {
        $('#utilization-range').change( function() {
          var range = $(this).val();
          updateCarrierCharts(range);
        });
      }

      function legendLabel(carrier, name) {
        value = carrier[name.toLowerCase() + '_total'];
        return name + ': ' + formatTransferBytes(value, 2);
      }

      function subtitleText(carrier) {
        var subtitleString = '';

        if (carrier) {
          subtitleString = 'Total Utilization: ' +
            formatTransferBytes(carrier.received_total + carrier.transmitted_total, 2);
        }

        return { text: subtitleString };
      }

      function tooltipPointFormatter(point) {
        return "<span style=\"color: " + point.color + ";\">\u25CF</span> " + point.series.name + ": <b>" + formatTransferBytes(point.y, 2) + "</b><br/>";
      }

      function cellularUtilizationChartOptions(carrier) {
        var exportEnabled = carrier ? carrier.carrier_series.length > 0 : false;
        var series = carrier ? carrier.carrier_series : [];
        var titleText = carrier ? 'Cellular Utilization for ' + carrier.carrier_name : 'Cellular Utilization';

        return {
          exporting: { enabled: exportEnabled },
          legend: { labelFormatter: function () { return legendLabel(carrier, this.name) }},
          series: series,
          subtitle: subtitleText(carrier),
          title: {
            style: { fontSize: '14px' },
            text: titleText
          },
          tooltip: {
            formatter: function() {
              var tooltipString = '<span style="font-size: .9em">' + Highcharts.dateFormat('%A, %b %d, %H:%M', this.x) + '</span>';
              var totalBytes = 0;

              $.each(this.points, function(i, point) {
                tooltipString += '<br/>' + tooltipPointFormatter(point);
                totalBytes += point.y;
              });

              tooltipString += '<br/>' +
                               '<span style="color: transparent;">\u25CF</span>' + '<b>' + ' Total: ' + formatTransferBytes(totalBytes, 2) + '</b>';

              return tooltipString;
            }
          },
          xAxis: { type: 'datetime' },
          yAxis: {
            labels: {
              formatter: function() { return formatTransferBytes(this.value, 2) }
            },
            min: 0,
            title: { text: null }
          }
        }
      }
    });
  </script>
<% end %>

<div id="carrier-charts">
  <div class="form form-inline text-right m-b">
    <div class="form-group">
      <label for="utilization-range">Range</label>
      <select class="form-control" id="utilization-range">
        <%= options_for_select(
                Measurement::Base::ALLOWED_RANGES.map{|e| [ e[:description], e[:value] ]},
                Measurement::Base::DEFAULT_RANGE ) %>
      </select>
    </div>
  </div>
  <div class="chart-container cellular-utilization"></div>
</div>

app/views/shared/charts/_cellular_utilization_chart_ibox.html.erb
<div>
  <div class="ibox">
    <div class="ibox-title">
      <h5>Cellular Utilization</h5>
    </div>
    <div class="ibox-content">
      <%= render partial: 'shared/charts/cellular_utilization_chart' %>
    </div>
  </div>
</div>

app/views/shared/charts/_connectivity_status_chart_ibox.html.erb
<div class="ibox">
  <div class="ibox-title">
    <h5>Connectivity</h5>
    <div class="ibox-tools">
      <a data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#connectivity-status-chart-helper">
        <i class="fa fa-question-circle"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="chart-header">
      <small>Last Updated: <%= timestamp_in_users_timezone(Time.now) %></small><br>
      <small>Number of Devices by Status in: <strong><%= current_organization_name %></strong><br></small>
    </div>
    <div class="chart-container">
      <div class="chart" id="connectivity-status"></div>
    </div>
  </div>
</div>

<%= render layout: 'layouts/helper_modal', locals: { modal_id: 'connectivity-status-chart-helper', modal_title: 'Connectivity Chart Help' } do %>
  <div class="modal-body">
    <p>
      The <strong>Connectivity</strong> graph represents the breakdown of the connectivity status for
      Deployed devices.  This graph only reports on the main statuses of Up / Down / Unreachable.
    </p>
    <dl>
      <dt>Up</dt>
      <dd>The device is online and is reachable through the application.</dd>
      <dt>Down</dt>
      <dd>The device is not reachable via the application.</dd>
      <dt>Unreachable</dt>
      <dd>The device has never checked into the application even though it is in a Deployed state.</dd>
    </dl>
  </div>
<% end %>

app/views/shared/charts/_deployed_status_chart_ibox.html.erb
<div class="ibox">
  <div class="ibox-title">
    <h5>Deployment</h5>
    <div class="ibox-tools">
      <a data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#deployed-status-chart-helper">
        <i class="fa fa-question-circle"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="chart-header">
      <small>Last Updated: <%= timestamp_in_users_timezone(Time.now) %></small><br>
      <small>Number of Devices by Status in: <strong><%= current_organization_name %></strong><br></small>
    </div>
    <div class="chart-container">
      <div class="chart" id="deployed-status"></div>
    </div>
  </div>
</div>

<%= render layout: 'layouts/helper_modal', locals: { modal_id: 'deployed-status-chart-helper', modal_title: 'Deployment Chart Help' } do %>
  <p>The <strong>Deployment</strong> graph represents the breakdown of Deployed / Undeployed devices in this organization.</p>
  <dl>
    <dt>Deployed</dt>
    <dd>
      Indicates the device should be monitored based on the events that are sent in by the device,
      and will be listed with a particular Deployed status. A device that is deployed will also generate
      notification alerts based on the events received and access to that device.
    </dd>
    <dt>Undeployed</dt>
    <dd>
      Indicates the device <strong><em>should not</em></strong> be monitored. Undeployed devices will be
      listed with a pause icon ( <i class="fa fa-pause"></i> ) as their status and with a gray status color.
      The application will still list details and events for undeployed devices, but these events will not generate any
      notification alerts.
    </dd>
  </dl>
<% end %>

app/views/shared/charts/_network_type_chart_ibox.html.erb
<div class="ibox">
  <div class="ibox-title">
    <h5>Cellular Network Type</h5>
    <div class="ibox-tools">
      <a data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#network-type-chart-helper">
        <i class="fa fa-question-circle"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <div class="chart-header">
      <small>Last Updated: <%= timestamp_in_users_timezone(Time.now) %></small><br>
      <small>Number of Devices by Status in: <strong><%= current_organization_name %></strong></small>
    </div>
    <div class="chart-container">
      <div class="chart" id="network-type"></div>
    </div>
  </div>
</div>

<%= render layout: 'layouts/helper_modal', locals: { modal_id: 'network-type-chart-helper', modal_title: 'Network Type Chart Help' } do %>
  <div class="modal-body">
    <p>
      The <strong>Cellular Network Type</strong> graph represents the Cellular Network Connectivity Type of Deployed
      cellular enabled devices.
    </p>
  </div>
<% end %>

app/views/shared/charts/_signal_strength_chart_ibox.html.erb
<div class="ibox">
  <div class="ibox-title">
    <h5>Signal Strength</h5>
    <div class="ibox-tools">
      <a data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#signal-strength-chart-helper">
        <i class="fa fa-question-circle"></i>
      </a>
    </div>
  </div>
  <div class="ibox-content">
    <small>Last Updated: <%= timestamp_in_users_timezone(Time.now) %></small><br>
    <small>Number of Devices by Status in: <strong><%= current_organization_name %></strong></small>
    <div class="chart-container">
      <div class="chart" id="signal-strength"></div>
    </div>
  </div>
</div>

<%= render layout: 'layouts/helper_modal', locals: { modal_id: 'signal-strength-chart-helper', modal_title: 'Signal Strength Chart Help' } do %>
  <div class="modal-body">
    <p>
      The <strong>Signal Strength Chart</strong> graph represents the number of deployed cellular devices and their
      reported signal strength percentage.
    </p>
  </div>
<% end %>

app/views/shared/charts/_wan_utilization_charts.html.erb
<% content_for :header_javascript_block  do %>
    <script type="text/javascript">
      var wanUtilizationChart = {};

      $(document).on('tabShown', '#device_details', function() {
        if ($('.chart.wan-utilization .highcharts-container').length == 0) {
          wanUtilizationChart = new WanUtilizationChartConstructor({mac: '<%= @presenter.device.mac %>'});
          wanUtilizationChart.load();
        }
        else { wanUtilizationChart.reflow(); }
      })
    </script>
<% end %>

<div class="wan-utilization-charts">
  <div class="form form-inline text-right m-b">
    <div class="form-group">
      <label for="wan-utilization-range">Range</label>
      <select class="form-control" id="wan-utilization-range">
        <%= options_for_select(
                Measurement::Base::ALLOWED_RANGES.map{|e| [ e[:description], e[:value] ]},
                Measurement::Base::DEFAULT_RANGE ) %>
      </select>
    </div>
  </div>

  <div class="title">
    WAN Utilization
    <a data-toggle="modal" data-backdrop="static" data-keyboard="false" data-target="#wan-utilization-chart-helper">
      <i class="fa fa-question-circle"></i>
    </a>
  </div>
  <div class="chart-container wan-utilization"></div>
</div>

<%= render layout: 'layouts/helper_modal', locals: { modal_id: 'wan-utilization-chart-helper', modal_title: 'WAN Utilization Chart Help' } do %>
  <p>
    The WAN utilization graphs shows you how much of the available bandwidth of your WAN link you are consuming.  Capacity of your WAN link might
    not always be the same in both directions, thus we have a different graph showing the usage separately of both: <b>Upload</b> and <b>Download</b>.
    <p> The device samples utilization measurements every minute. If Data Usage is enabled in the settings, then
        the device will take the average of five samples to provide a single measurement resulting in twelve measurements per hour for reporting.
        This is how we calculate the Average Used.
    <p> If bandwidth testing has been turned on for this device in the Class of Service settings, then the device will perform bandwidth tests
        and include the results of those tests in the measurements used in the reporting.  If this setting is turned off we would only display
        the Average Used line.
    <p>The graphs depict several types of bandwidth measurements over your chosen time range:
    <b>High Water Mark</b>, <b>Maximum Used</b> and <b>Average Used</b>.
    <p>The three time ranges you can select from are: 24 hours, 7 days, or 30 days. If the time range is 24 hours, then the time interval
       for each data point is 1 hour, for the 7 and 30 days ranges this interval is 1 day.  A data point represents the measurements collected from
       the time of the current data point to the next data point.
    <p>The legend of your graph dynamically adjusts to your data usage and shows either KB/s or MB/s.
    The hover popup will show more details of the measurements and uses always KB/s
  </p>

  <dl>
    <dt>High Water Mark</dt>
    <dd>
      Each data point of this line shows the average value of the High Water Mark (HWM) measurements received per time interval,
      and gives an estimate of the available bandwidth during that time interval.
      The HWM are obtained from the bandwidth tests.
    </dd>
    <dt>Maximum Used</dt>
    <dd>
      Each data point of this line shows the most data usage that was observed per time interval.
      This is an indicator of the bandwidth you get during traffic bursts.
    </dd>

    <dt>Average Used</dt>
    <dd>
      Each data point of this line shows the average data usage that was observed during this time interval during the selected range.
      The Average Used is derived from measurements collected by the device as specified by the Data Usage settings for this device.
    </dd>

    <dt>Max Percentage Used</dt>
    <dd>
      Each data point of this line shows the Maximum Used as a percentage of the High Water Mark during this time interval.
      This percentage indicates how close your actual bandwidth is compared to the tested bandwidth.
    </dd>

    <dt>Max Percentage by Range</dt>
    <dd>
      The highest recorded value for the Max Percentage Used over the selected time range (24 hours, 7 days, or 30 days).
    </dd>
  </dl>
<% end %>