config/routes.rb
AviewWebapp::Application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  apipie

  namespace :api, defaults: { format: :json } do
    api_version(module: 'V1', path: { value: 'v1' }, default: false) do
      namespace :auth do
        resources :att_bc, only: [:create, :index]
      end
    end

    api_version(module: 'V2', path: { value: 'v2' }, default: true) do
      resources :devices, only: [:index, :show] do
        member do
          patch :update_settings
        end
      end
      resources :accounts, only: [:update] do
        member do
          patch :update_password
          patch :update_filter
          patch :clear_filter
          patch :generate_api_token
        end

        resources :devices, only: [:index, :show, :update] do
        end

        resources :notification_subscriptions do
          collection do
            get :search
            get :reset
          end
        end

        resources :notification_profiles do
          member do
            get :subscriptions
          end
        end
      end
      resources :users
      resources :roles
      resources :sites
      resources :passwords, only: [:update]
      resources :organizations do
        member do
          get :abilities
        end
      end
    end

    api_version(module: 'V3', path: { value: 'v3' }, default: false) do
      resources :devices, only: [:update] do
        member do
          patch :update_location
          patch :clear_location
        end

        resources :contacts, only: [:new, :show, :update, :create, :index, :destroy]
        resources :dial_tests, only: [:index]
      end
    end

    api_version(module: 'V4', path: { value: 'v4' }, default: false) do
      resources :devices, only: [:index] do
        collection do
          get :usage
        end
      end
    end
  end

  scope module: :api, defaults: {format: :json} do
    namespace :device_configurations do
      resources :v2, only: [:show]
    end

    namespace :certificates do
      resources :v2, only: [:create]
      post '/', controller: 'v2', action: :create
    end
  end

  post "/pdns/lookup", to: "power_dns_backend#lookup"
  post "/pdns/getDomainMetadata", to: proc { [404, {}, ['']] }
  post "/pdns/calculateSOASerial", to: proc { [404, {}, ['']] }

  resource :dashboard, only: :show do
    collection do
      get 'device_table'
    end
  end

  resource :highcharts, only: [] do
    collection do
      get 'cellular_utilization'
      get 'connectivity_status_chart'
      get 'deployed_status_chart'
      get 'ids_alerts_histogram'
      get 'network_type_chart'
      get 'signal_strength_chart'
      get 'intelliflow_app_usage'
      get 'intelliflow_app_usage_over_time'
      get 'wan_utilization'
    end
  end

  root :to => 'dashboards#show'

  devise_for :users
  resources :users do
    resources :permissions

    collection do
      resource :activation, controller: :activations, only: [:new, :create]
    end
  end

  resources :account, :except => :show do
    patch :update, :on => :collection
    patch :change, :on => :collection
    get   :change, :on => :collection
    get   :change_password, :on => :collection
    patch :update_password, :on => :collection
    get   :api, :on => :collection
    patch :generate_api_token, :on => :collection
  end

  resources :searches, only: [:index, :new]

  resources :notifications do
    get :since, :on => :collection
  end

  post 'data_tables/devices/(:data_table_class)/(:reference_id)', to: 'data_tables#devices', as: :devices_data_tables
  post 'data_tables/events/(:mac)', to: 'data_tables#events', as: :events_data_tables
  # TODO: Get rid of index route and action, used by reports
  resources :data_tables, only: [] do
    collection do
      post :searches
      post :sites
      post :users
      post :notifications
      post :intelliflow_client_usage
      post :groups
      post :group_devices
    end
  end

  resources :devices, except: :create do
    collection do
      get :vpn_gateway
      get :wifi
      get :legacy_cellular
      get :cellular
      get :dial_to_ip
      get :remote_manager
      get :ucpe
      get :to_csv

      post :with_selected
      post :vpn_gateway
      post :wifi
      post :legacy_cellular
      post :cellular
      post :dial_to_ip
      post :remote_manager
      post :ucpe
    end

    member do
      get :terminal
      get :toggle_deployment
      get :replace
      get :events
      get :remove_contact
      get :commands_list
      get :remote
      get :organization_configurations
      get :move_to_organization

      post :replace_with
      post :add_contact

      patch :remote
      patch :save_configuration
    end

    resources :modems, only: :destroy

    resources :charts do
      collection do
        get :signal
        get :network
      end
    end

    resources :device_associations do
      collection do
        get :table
      end
    end

    get "/events/since" => "devices#events_since"

    namespace :configuration do
      resource :network, only: [:show, :update]
      resource :internet_routes, only: [:show, :create, :update, :destroy] do
        delete :destroy_all
      end
      resource :cascaded_networks, only: [:show, :create, :update, :destroy] do
        delete :destroy_all
      end
    end

    resources :ids_alerts, only: :index
  end

  resources :tunnel_servers, only: [:index, :show] do
    member do
      get :ip_addresses
    end
  end

  resources :configurations

  get '/configurations/:id/device_config', to: 'legacy_configurations#device_config'

  constraints subdomain: "#{Settings.subdomains.configurations}" do
    get '/:id', to: 'legacy_configurations#device_config'
  end

  resources :legacy_configurations do
    collection do
      get :inherited_values
      get :available_parents
      get :organization_configurations
      get :parent_configuration
      get :exists_for_organization
      get :cellular
    end

    member do
      post  :copy
      get   :device_config
    end
  end

  resources :reports do
    member do
      post :export
    end

    collection do
      get :availability
      get :cellular_network_type
      get :cellular_utilization
      get :cellular_signal_strength
      get :vig
      get :finished_generating
    end
  end

  resources :chart_data do
    get :device, :on => :collection
  end

  resources :sites do
    get :to_csv, :on => :collection

    collection do
      get :search
    end
  end

  resources :organizations do
    member do
      get   :edit_logo
      patch :update_logo
      get   :edit_footer
      patch :update_footer
      patch :update_device_settings
      get :actions_menu
    end

    collection do
      post  :move_devices_to
      get :search
    end

    resources :roles do
      get :abilities
    end

    resources :permissions
    resources :data_plans do
      collection do
        post :move_devices_to
        get :exists_for_organization
      end
    end


  end

  resources :maps do
    get :pins, :on => :collection
    get :alert_pins, :on => :collection
  end

  resources :events do
    get :new_since, :on => :collection
    get :since, :on => :collection
  end

  resources :device_configurations, except: [:index] do
    collection do
      get '/v2/:mac', to: 'device_configurations#device'
      get :dial_to_ip
      get :remote_manager
      get :cellular
      get :ucpe
      get :exists_for_organization
    end
    member do
      get   :edit_linked_devices
      patch :update_linked_devices
      post  :copy
    end
  end

  resources :device_firmwares, only: [] do
    member do
      get :schema_file
    end
  end

  get '/admin', :to => 'admin#index'

  get '/vvig_pnc', :to => 'vvig_pnc#index'

  get '/vvig_pnc/data', :to => 'vvig_pnc#get_data'

  namespace :admin do
    get :server_log

    get :device_statistics

    resources :dns

    resources :imports do
      collection do
        get     :template
        delete  :destroy_all
      end

      member do
        get :objects
      end
    end

    resources :certificates, only: [:index, :destroy] do
      member do
        patch :approve
      end
    end

    resources :customer_services, except: [:show]

    resources :settings, only: [] do
      collection do
        patch :update
      end
    end
  end

  resources :device_models, only: [:index] do
    resources :device_firmwares, only: [:index]

    member do
      get :firmware_select
    end
  end

  resources :groups do
    collection do
      post :destroy_multiple
    end

    member do
      get :device_search
      post :add_devices
      post :remove_devices
      get :edit_firmware
      post :update_firmware
      get :group_widgets
      get :configuration
    end
  end

  namespace :services, defaults: { format: :json } do
    scope :configurations do
      get   'device/:device_id', to: 'configurations#device'
      patch 'device/:device_id', to: 'configurations#update_device'
      get   'schemas/:model/ui', to: 'configurations/schemas#ui'
    end
  end

  post "/feedback" => "feedback#create"

  get "/cellular_locations" => "cellular_locations#show"

  get "/401" => "errors#unauthorized"
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  get '*unmatched_route', via: :all, to: 'errors#not_found'
end

app/controllers/api/device_configurations/v2_controller.rb
module Api

  module DeviceConfigurations

    class V2Controller < Api::ApiController

      before_filter :validate_sdn!
      before_filter :set_modified_at_header, only: :show
      after_filter  :save_config_checked_at, only: :show

      around_action :show_metrics, only: :show

      # GET /device_configurations/v2/002704030201.json
      def show
        if device.blank?
          ops_metric_increment 'configurations.device_not_found'
          render json: {message: 'Device Not Found'}, status: :not_found
        elsif device.configuration.blank?
          ops_metric_increment 'configurations.not_found'
          render json: {message: 'Configuration Not Found'}, status: :not_found
        elsif !config_modified?
          ops_metric_increment 'configurations.not_modified'
          render json: {message: 'Configuration Not Modified'}, status: :not_modified
        else
          ops_metric_increment 'configurations.rendered'
          if Settings.views.device.configuration_inheritance
            render json: device.configuration.compiled_settings
          else
            render json: device.configuration.description
          end
        end
      end

      private

      def show_metrics(&block)
        ops_metric_measure 'configurations.elapsed' do
          yield
        end
      end

      def validate_sdn!
        distinguished_name = ::DistinguishedName.parse(sdn)

        unless distinguished_name.common_name_matches?(params[:id], 'universal')
          ops_metric_increment 'configurations.unauthorized'
          render json: { message: 'Forbidden' }, status: :forbidden
        end
      end

      def save_config_checked_at
        device.update_column(:configuration_checked_at, Time.now) if device
      end

      def set_modified_at_header
        if device && device.configuration && modified_at
          response.headers['Last-Modified'] = modified_at.rfc2822
        end
      end

      def device
        @device ||= Device.where('upper(mac) = upper(?)', params[:id]).first
      end

      def modified_since
        @modified_since ||= begin
          Time.rfc2822(request.env['HTTP_IF_MODIFIED_SINCE']) if request.env['HTTP_IF_MODIFIED_SINCE']
        rescue
          nil
        end
      end

      def modified_at
        @modified_at ||= begin
          if device.configuration_associated_at && (device.configuration_associated_at > device.configuration.updated_at)
            device.configuration_associated_at
          else
            device.configuration.updated_at
          end
        end
      end

      def config_modified?
        return true unless modified_since
        modified_at > modified_since
      end

    end
  end
end

app/helpers/device_configurations_helper.rb
module DeviceConfigurationsHelper

  def can_modify_device_configurations?
    @can_modify_device_configurations ||= Pundit.policy(current_user, DeviceConfiguration).modify?
  end


  def user_firmwares_selection_string
    return @user_firmwares_selection_string if @user_firmwares_selection_string

    @user_firmwares_selection_string = \
      if Pundit.policy(current_user, DeviceFirmware).assign_non_production?
        'sort_device_firmwares_reverse'
      else
        'sort_active_device_firmwares_reverse'
      end

    @user_firmwares_selection_string
  end

end

app/views/device_configurations/_copy_button.html.erb
<%= link_to "#copyDeviceConfigurationModal",
            class: "btn btn-xs btn-success",
            title: "Copy Device Configuration",
            role: "button",
            data: {toggle: 'modal'} do %>
  <i class="fa fa-clone"></i> Copy
<% end %>

<div class="modal inmodal fade in" id="copyDeviceConfigurationModal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="event-information-content">
      <div class="modal-header">
        <button type="button" class="close copyConfigurationClose" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="copyDeviceConfigurationModal">Copy Device Configuration</h3>
      </div>
      <div class="modal-body">
        <%= form_for @device_configuration, url: {action: :copy}, method: :post, html: {class: 'form-horizontal'} do |f| %>
          <div class="form-group">
            <label class="col-md-3 control-label" for="name">New Name</label>
            <div class='col-md-7'>
              <%= text_field_tag :name, '', placeholder: 'Enter name for new configuration', class: 'form-control' %>
            </div>
          </div>
          <div class="modal-footer">
            <button class="btn copyDeviceConfigurationClose" data-dismiss="modal" aria-hidden="true">Close</button>
            <%= f.submit 'Copy', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/device_configurations/_delete_button.html.erb
<% if @device_configuration.persisted? %>
    <%= link_to device_configuration_path(@device_configuration),
                method: :delete,
                data: {
                    confirm: "Are you sure you want to delete this configuration?\n"\
                    "There are #{@device_configuration.all_associated_devices.count} devices associated with this configuration.\n"\
                    "This action can not be undone."
                },
                class: "btn btn-xs btn-danger" do %>
        <i class="fa fa-times"></i> Delete
    <% end %>
<% end %>

app/views/device_configurations/_edit_button.html.erb
<%= link_to edit_device_configuration_path(@device_configuration),
            class: "btn btn-xs btn-info",
            title: "Edit Device Configuration" do %>
  <i class="fa fa-pencil"></i> Edit
<% end %>

app/views/device_configurations/_edit_linked_devices_button.html.erb
<% if @device_configuration.persisted? && Pundit.policy(current_user, @device_configuration).modify? %>
  <%= link_to edit_linked_devices_device_configuration_path(@device_configuration),
              :class => "btn btn-xs btn-info" do %>
    <i class="fa fa-edit"></i> Link Devices
  <% end %>
<% end %>

app/views/device_configurations/_new_button.html.erb
<%= link_to new_device_configuration_path(category_id: category_id),
            class: "btn btn-primary btn-xs m-l",
            title: "Add Cellular Configuration" do %>
  <i class="fa fa-plus-circle"></i> New
<% end %>

app/views/device_configurations/destroy.js.erb
var alert = "<%= j alert_success message: t('configurations.destroyed', name: @device_configuration.name) %>";

$('#configurations-table').DataTable().ajax.reload(function() {
  $('div.wrapper-content').prepend(alert);
  setAlertExpiration($('div.wrapper-content > .alert'));
});

app/views/device_configurations/edit.html.erb
<%= render 'shared/page_header', locals: { title: 'Edit Device Configuration' } %>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t("Device Configurations") %></h5>
          <div class="pull-right">
            <%= render 'new_button', category_id: @category.id %>
            <%= render 'edit_linked_devices_button' %>
            <%= render 'delete_button' %>
          </div>
        </div>
        <div class="ibox-content">
          <%= form_for @device_configuration, :html => { class: "form-horizontal", id: 'device-configuration-form' } do |f| %>
            <% content_for :device_configuration_form_actions do %>
              <div class="form-actions">
                <%= f.submit 'Update', class: 'btn btn-primary', id: 'save-device-configuration' %>
                <%= link_to "Cancel", device_configuration_path(@device_configuration), :class => "btn btn-white" %>
              </div>
            <% end %>
            <%= render :partial => "form", :locals => { :f => f } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/device_configurations/edit_linked_devices.html.erb
<% content_for :header_javascript_block  do %>
  <script type="text/javascript">
    function initDataTable(columns, table) {
      table.DataTable({
        columns: getColumnSettings(columns),
        dom: "<'row'<'col-sm-12'l>>" +
            "<'row'<'col-sm-4'i><'col-sm-8'p>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-4'i><'col-sm-8 lower'<'circle-border-spinner'>p>>",
        lengthMenu: [[ 25, 50, 100, 500 ], [ 25, 50, 100, 500 ]],
        order: getSorting(columns, table),
        pageLength: 100,
        scrollX: true,
        scrollY: false
      });
    }

    $(document).ready(function () {
      $('.checkbox-toggler').on('change', function() {
        var disabled = "[disabled='disabled']";
        $(this).is(':checked') ?
            $('.checkbox-togglee').not(disabled).prop('checked', true) :
            $('.checkbox-togglee').not(disabled).prop('checked', false);
      });
    });
  </script>
<% end %>

<%= render 'shared/page_header', locals: { title: 'Link Devices To Device Configuration' } %>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t("Device Configurations") %></h5>
        </div>
        <div class="ibox-content form-horizontal">
          <div class="form-group">
            <%= label_tag :name, 'Name', class: 'control-label col-lg-2' %>
            <div class='col-lg-8'>
              <%= text_field_tag :name, @device_configuration.name, readonly: true, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag :organization_id, 'Organization', class: 'control-label col-lg-2' %>
            <div class='col-lg-8'>
              <%= text_field_tag :organization_id, @device_configuration.organization.name, readonly: true, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag :category_id, 'Category', class: 'control-label col-lg-2' %>
            <div class='col-lg-8'>
              <%= text_field_tag :category_id, @device_configuration.category.name, readonly: true, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag :model, nil, class: 'control-label col-lg-2' %>
            <div class='col-lg-8'>
              <%= text_field_tag :model, @device_configuration.device_model.name, readonly: true, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= label_tag :firmware, nil, class: 'control-label col-lg-2' %>
            <div class='col-lg-8'>
              <%= text_field_tag :version, @device_configuration.device_firmware.version, readonly: true, class: 'form-control' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t("Devices") %></h5>
        </div>
        <div class="ibox-content">
          <%= form_tag update_linked_devices_device_configuration_path, method: :patch do %>
            <%= hidden_field_tag :filter, params[:filter] %>
            <div class= 'table vs-target-wrapper'>
              <table class='dataTable display table table-striped table-bordered table-hover vs-table' id='device-table'>
                <thead>
                <tr>
                  <th class="dt-center"><%= check_box_tag :toggle, nil, false, {:class => 'checkbox-toggler'} %></th>
                  <th class="sortable" name="status">Status</th>
                  <th class="sortable" name="id"><%= t(:mac) %></th>
                  <th class="sortable" name="host"><%= t(:primary_ip) %></th>
                  <th class="sortable" name="category">Category</th>
                  <th class="sortable" name="model">Model</th>
                  <th class="sortable" name="organization">Organization</th>
                  <th class="sortable" name="site">Site</th>
                  <th class="sortable" name="firmware">Firmware</th>
                  <th class="sortable" name="country">Country</th>
                  <th class="sortable" name="last_heartbeat">Last Heartbeat</th>
                </tr>
                </thead>
                <tbody>
                <% @devices.each do |device| %>
                  <tr>
                    <td class="dt-center">
                      <%= hidden_field_tag("selected_records[#{device.id}]", '0') %>
                      <%= check_box_tag(
                              "selected_records[#{device.id}]",
                              '1',
                              @checked_lambda[device],
                              class:    'checkbox-togglee',
                              disabled: @checked_lambda[device]
                          ) %>
                    </td>
                    <td class="text-center">
                      <i class="<%= device.status_indicator %>" data-toggle='tooltip' data-placement='right' data-title="<%= device.status_title %>"></i>
                      <span class='sr-only'><%= device.status_title %></span>
                    </td>
                    <td><%= device.mac %></td>
                    <td><%= device.host %></td>
                    <td><%= device.category_name %></td>
                    <td><%= device.series_name %></td>
                    <td><%= device.organization.name %></td>
                    <td><%= device.site_name %></td>
                    <td><%= device.firmware %></td>
                    <td><%= device.location.try(:country).try(:code)%></td>
                    <td><%= timestamp_in_users_timezone(device.last_heartbeat_at) %></td>
                  </tr>
                <% end %>
                </tbody>
              </table>
              <div class="form-actions">
                <%= submit_tag 'Link Selected Devices', class: 'btn btn-primary m-r' %>
                <%= submit_tag 'Link All Devices',      class: 'btn btn-danger m-r' %>
                <%= link_to "Cancel", device_configuration_path(@device_configuration), :class => "btn btn-white" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/device_configurations/show.html.erb
<% content_for :header_javascript_block  do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('[rel = popover]').popover({trigger: 'hover'});
      $('[data-toggle="tooltip"]').tooltip({trigger: 'hover'});
    });

   var accConfigForm = new AccConfigForm($('#show-device-configuration'), $('.device-configuration-cooked'));

    function initDataTable(columns, table) {
      table.DataTable({
        colReorder: true,
        columns: getColumnSettings(columns),
        dom: "<'row'<'col-sm-12'l>>" +
            "<'row'<'col-sm-4'i><'col-sm-8'p>>" +
            "<'row'<'col-sm-12'tr>>" +
            "<'row'<'col-sm-4'i><'col-sm-8 lower'<'circle-border-spinner'>p>>",
        lengthMenu: [[ 25, 50, 100, 500 ], [ 25, 50, 100, 500 ]],
        pageLength: 100,
        scrollX: true,
        scrollY: false
      });
    }
  </script>
<% end %>

<%= render 'shared/page_header', locals: { title: 'Show Device Configuration' } %>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t("Device Configurations") %></h5>
          <% if Pundit.policy(current_user, @device_configuration).modify? %>
          <div class="pull-right">
            <%= render 'edit_button' %>
            <%= render 'copy_button' %>
            <%= render 'delete_button' %>
          </div>
          <% end %>
        </div>
        <div class="ibox-content">
          <form class="form-horizontal">
            <div id="show-device-configuration">
              <div class="form-group">
                <%= label_tag :name, 'Name', class: 'control-label col-lg-2' %>
                <div class='col-lg-8'>
                  <%= text_field_tag :name, @device_configuration.name, disabled: true, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :organization_id, 'Organization', class: 'control-label col-lg-2' %>
                <div class='col-lg-8'>
                  <%= text_field_tag :organization_id, @device_configuration.organization.name, disabled: true, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :category_id, 'Category', class: 'control-label col-lg-2' %>
                <div class='col-lg-8'>
                  <%= text_field_tag :category_id, @device_configuration.category.name, disabled: true, class: 'form-control' %>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :model, nil, class: 'control-label col-lg-2' %>
                <div class='col-lg-8'>
                  <%= text_field_tag :model, @device_configuration.device_model.name, disabled: true, class: 'form-control' %>
                </div>
              </div>

              <%= hidden_field_tag :device_firmware_id, @device_configuration.device_firmware_id, id: 'device_configuration_device_firmware_id' %>

              <div class="form-group">
                <%= label_tag :firmware, nil, class: 'control-label col-lg-2' %>
                <div class='col-lg-8'>
                  <% if @device_configuration.device_firmware.production? %>
                    <span class="form-control" disabled="true"><%= @device_configuration.device_firmware.version %></span>
                  <% else %>
                    <span class="form-control" disabled="true">
                      <p class="alert-info"><%= @device_configuration.device_firmware.version %></p>
                    </span>
                  <% end %>
                  <span class="help-block m-b-none">Blue highlight denotes non-production firmware</span>
                </div>
              </div>

              <div class="form-group">
                <%= label_tag :grace_period_duration, 'Grace Period Duration', class: 'control-label col-lg-2' %>
                <div class="col-lg-8">
                  <div class="input-group">
                    <%= text_field_tag :grace_period_duration, @device_configuration.grace_period_duration, disabled: true, class: 'form-control' %>
                    <%= render partial: '/legacy_configurations/popover', :locals => {field: popover_data(:grace_period_duration)} %>
                  </div>
                </div>
              </div>

              <div class="form-group">
                <div class='col-lg-12 controls'>
                  <div class="device-configuration-cooked accfg-panel"></div>
                  <div class="device-configuration-raw" style="display: none;">
                    <%= text_area_tag :description, @device_configuration.description, id: 'device_configuration_description', disabled: true %>
                  </div>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5>Linked Devices</h5>
          <div class="pull-right">
            <%= render 'edit_linked_devices_button' %>
          </div>
        </div>
        <div class="ibox-content">
          <div class= 'table vs-target-wrapper'>
            <table class='dataTable display compact table table-striped table-bordered table-hover vs-table' id='device-table'>
              <thead>
              <tr>
                <th class="sortable" name="status">Status</th>
                <th class="sortable" name="id"><%= t(:mac) %></th>
                <th class="sortable" name="host"><%= t(:primary_ip) %></th>
                <th class="sortable" name="category">Category</th>
                <th class="sortable" name="model">Model</th>
                <th class="sortable" name="organization">Organization</th>
                <th class="sortable" name="site">Site</th>
                <th class="sortable" name="firmware">Firmware</th>
                <th class="sortable" name="country">Country</th>
                <th class="sortable" name="last_heartbeat">Last Heartbeat</th>
              </tr>
              </thead>
              <tbody>
              <% @devices.each do |device| %>
                <tr>
                  <td><i class="<%= device.status_indicator %>" data-toggle='tooltip' data-placement='right' data-title="<%= device.status_title %>"></i><span class='sr-only'><%= device.status_title %></span></td>
                  <td><%= link_to device.mac, device_path(device) %></td>
                  <td><%= host_link(device) %></td>
                  <td><%= device.category_name %></td>
                  <td><%= device.series_name %></td>
                  <td><%= link_to device.organization.name, device.organization %></td>
                  <td><%= link_to device.site_name, device.site %></td>
                  <td><%= device.firmware %></td>
                  <td><%= device.location.try(:country).try(:code)%></td>
                  <td><%= timestamp_in_users_timezone(device.last_heartbeat_at) %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>