config/routes.rb
AviewWebapp::Application.routes.draw do

  get 'errors/not_found'

  get 'errors/internal_server_error'

  apipie

  namespace :api, defaults: { format: :json } do
    api_version(module: 'V1', path: { value: 'v1' }, default: false) do
      namespace :auth do
        resources :att_bc, only: [:create, :index]
      end
    end

    api_version(module: 'V2', path: { value: 'v2' }, default: true) do
      resources :devices, only: [:index, :show] do
        member do
          patch :update_settings
        end
      end
      resources :accounts, only: [:update] do
        member do
          patch :update_password
          patch :update_filter
          patch :clear_filter
          patch :generate_api_token
        end

        resources :devices, only: [:index, :show, :update] do
        end

        resources :notification_subscriptions do
          collection do
            get :search
            get :reset
          end
        end

        resources :notification_profiles do
          member do
            get :subscriptions
          end
        end
      end
      resources :users
      resources :roles
      resources :sites
      resources :passwords, only: [:update]
      resources :organizations do
        member do
          get :abilities
        end
      end
    end

    api_version(module: 'V3', path: { value: 'v3' }, default: false) do
      resources :devices, only: [:update] do
        member do
          patch :update_location
          patch :clear_location
        end

        resources :contacts, only: [:new, :show, :update, :create, :index, :destroy]
        resources :dial_tests, only: [:index]
      end
    end

    api_version(module: 'V4', path: { value: 'v4' }, default: false) do
      resources :devices, only: [:index] do
        collection do
          get :usage
        end
      end
    end
  end

  scope module: :api, defaults: {format: :json} do
    namespace :device_configurations do
      resources :v2, only: [:show]
    end

    namespace :certificates do
      resources :v2, only: [:create]
      post '/', controller: 'v2', action: :create
    end
  end

  post "/pdns/lookup", to: "power_dns_backend#lookup"
  post "/pdns/getDomainMetadata", to: proc { [404, {}, ['']] }
  post "/pdns/calculateSOASerial", to: proc { [404, {}, ['']] }

  resource :dashboard, only: :show do
    collection do
      get 'device_table'
    end
  end

  resource :highcharts, only: [] do
    collection do
      get 'cellular_utilization'
      get 'connectivity_status_chart'
      get 'deployed_status_chart'
      get 'ids_alerts_histogram'
      get 'network_type_chart'
      get 'signal_strength_chart'
      get 'intelliflow_app_usage'
      get 'intelliflow_app_usage_over_time'
      get 'wan_utilization'
    end
  end

  root :to => 'dashboards#show'

  devise_for :users
  resources :users do
    resources :permissions

    collection do
      resource :activation, controller: :activations, only: [:new, :create]
    end
  end

  resources :account, :except => :show do
    patch :update, :on => :collection
    patch :change, :on => :collection
    get   :change, :on => :collection
    get   :change_password, :on => :collection
    patch :update_password, :on => :collection
    get   :api, :on => :collection
    patch :generate_api_token, :on => :collection
  end

  resources :searches, only: [:index, :new]

  resources :notifications do
    get :since, :on => :collection
  end

  post 'data_tables/devices/(:data_table_class)/(:reference_id)', to: 'data_tables#devices', as: :devices_data_tables
  post 'data_tables/events/(:mac)', to: 'data_tables#events', as: :events_data_tables
  # TODO: Get rid of index route and action, used by reports
  resources :data_tables, only: [] do
    collection do
      post :searches
      post :sites
      post :users
      post :notifications
      post :intelliflow_client_usage
      post :groups
      post :group_devices
    end
  end

  resources :devices, except: :create do
    collection do
      get :vpn_gateway
      get :wifi
      get :legacy_cellular
      get :cellular
      get :dial_to_ip
      get :remote_manager
      get :ucpe
      get :to_csv

      post :with_selected
      post :vpn_gateway
      post :wifi
      post :legacy_cellular
      post :cellular
      post :dial_to_ip
      post :remote_manager
      post :ucpe
    end

    member do
      get :terminal
      get :toggle_deployment
      get :replace
      get :events
      get :remove_contact
      get :commands_list
      get :remote
      get :organization_configurations
      get :move_to_organization

      post :replace_with
      post :add_contact

      patch :remote
      patch :save_configuration
    end

    resources :modems, only: :destroy

    resources :charts do
      collection do
        get :signal
        get :network
      end
    end

    resources :device_associations do
      collection do
        get :table
      end
    end

    get "/events/since" => "devices#events_since"

    namespace :configuration do
      resource :network, only: [:show, :update]
      resource :internet_routes, only: [:show, :create, :update, :destroy] do
        delete :destroy_all
      end
      resource :cascaded_networks, only: [:show, :create, :update, :destroy] do
        delete :destroy_all
      end
    end

    resources :ids_alerts, only: :index
  end

  resources :tunnel_servers, only: [:index, :show] do
    member do
      get :ip_addresses
    end
  end

  resources :configurations

  get '/configurations/:id/device_config', to: 'legacy_configurations#device_config'

  constraints subdomain: "#{Settings.subdomains.configurations}" do
    get '/:id', to: 'legacy_configurations#device_config'
  end

  resources :legacy_configurations do
    collection do
      get :inherited_values
      get :available_parents
      get :organization_configurations
      get :parent_configuration
      get :exists_for_organization
      get :cellular
    end

    member do
      post  :copy
      get   :device_config
    end
  end

  resources :reports do
    member do
      post :export
    end

    collection do
      get :availability
      get :cellular_network_type
      get :cellular_utilization
      get :cellular_signal_strength
      get :vig
      get :finished_generating
    end
  end

  resources :chart_data do
    get :device, :on => :collection
  end

  resources :sites do
    get :to_csv, :on => :collection

    collection do
      get :search
    end
  end

  resources :organizations do
    member do
      get   :edit_logo
      patch :update_logo
      get   :edit_footer
      patch :update_footer
      patch :update_device_settings
      get :actions_menu
    end

    collection do
      post  :move_devices_to
      get :search
    end

    resources :roles do
      get :abilities
    end

    resources :permissions
    resources :data_plans do
      collection do
        post :move_devices_to
        get :exists_for_organization
      end
    end


  end

  resources :maps do
    get :pins, :on => :collection
    get :alert_pins, :on => :collection
  end

  resources :events do
    get :new_since, :on => :collection
    get :since, :on => :collection
  end

  resources :device_configurations, except: [:index] do
    collection do
      get '/v2/:mac', to: 'device_configurations#device'
      get :dial_to_ip
      get :remote_manager
      get :cellular
      get :ucpe
      get :exists_for_organization
    end
    member do
      get   :edit_linked_devices
      patch :update_linked_devices
      post  :copy
    end
  end

  resources :device_firmwares, only: [] do
    member do
      get :schema_file
    end
  end

  get '/admin', :to => 'admin#index'

  get '/vvig_pnc', :to => 'vvig_pnc#index'

  get '/vvig_pnc/data', :to => 'vvig_pnc#get_data'

  namespace :admin do
    get :server_log

    get :device_statistics

    resources :dns

    resources :imports do
      collection do
        get     :template
        delete  :destroy_all
      end

      member do
        get :objects
      end
    end

    resources :certificates, only: [:index, :destroy] do
      member do
        patch :approve
      end
    end

    resources :customer_services, except: [:show]

    resources :settings, only: [] do
      collection do
        patch :update
      end
    end
  end

  resources :device_models, only: [:index] do
    resources :device_firmwares, only: [:index]

    member do
      get :firmware_select
    end
  end

  resources :groups do
    collection do
      post :destroy_multiple
    end

    member do
      get :device_search
      post :add_devices
      post :remove_devices
      get :edit_firmware
      post :update_firmware
      get :group_widgets
      get :configuration
    end
  end

  namespace :services, defaults: { format: :json } do
    scope :configurations do
      get   'device/:device_id', to: 'configurations#device'
      patch 'device/:device_id', to: 'configurations#update_device'
      get   'schemas/:model/ui', to: 'configurations/schemas#ui'
    end
  end

  post "/feedback" => "feedback#create"

  get "/cellular_locations" => "cellular_locations#show"

  get "/401" => "errors#unauthorized"
  get "/404" => "errors#not_found"
  get "/500" => "errors#internal_server_error"

  get '*unmatched_route', via: :all, to: 'errors#not_found'
end

app/controllers/reports_controller.rb
require 'will_paginate/array'
require 'vig_report'

class ReportsController < ApplicationController
  include Operations::Metrics::Helpers

  before_filter :base_breadcrumbs, :except => [:create, :finished_generating]
  before_filter :get_report, only: [:show, :export, :destroy]

  around_action :show_metrics, only: :show

  def index
    respond_to do |format|
      format.html do
        add_breadcrumb "History", reports_path
        @presenter = Presenters::Reports::Index.new(view_context)
      end

      format.json do
        render json: ReportsDataTable.new(view_context)
      end
    end
  end

  def show
    redirect_to reports_path and return if @report.nil?
    add_breadcrumb @report.title,
                   url_for(controller: :reports, action: @report.report_type, only_path: true) if @report.title.present?
    add_breadcrumb timestamp_in_users_timezone(@report.created_at), report_path(@report)
  end

  def export
    if @report
      filename = "#{@report.report_type}-report-#{@report.id}-export"
      options = { column_headers: params['column-headers'], column_values: params['column-values'], report: @report }
      data_table = ReportDataTable.new(options)
      respond_to do |format|
        format.csv { send_data data_table.to_csv, type: 'text/csv', filename: "#{filename}.csv" }
        format.xlsx { send_data data_table.to_xlsx, type: 'application/xlsx', filename: "#{filename}.xlsx" }
      end
    else
      flash[:error] = t '.error'
      redirect_to reports_path
    end
  end

  def availability
    @presenter = Presenters::Reports::Availability.new(view_context)
    @report = @presenter.report
    add_breadcrumb 'Availability', '#'
    render :new
  end

  def cellular_network_type
    @presenter = Presenters::Reports::CellularNetworkType.new(view_context)
    @report = @presenter.report
    add_breadcrumb 'Cellular Network Type', '#'
    render :new
  end

  def cellular_utilization
    @presenter = Presenters::Reports::CellularUtilization.new(view_context)
    @report = @presenter.report
    add_breadcrumb 'Cellular Utilization', '#'
    render :new
  end

  def cellular_signal_strength
    @presenter = Presenters::Reports::CellularSignalStrength.new(view_context)
    @report = @presenter.report
    add_breadcrumb 'Cellular Signal Strength', '#'
    render :new
  end

  def vig
    @presenter = Presenters::Reports::Vig.new(view_context)
    @report = @presenter.report
    add_breadcrumb 'VIG', '#'
    render :new
  end

  def create
    if @report = current_user.reports.create(params: params[:report])
      @report_queue = TorqueBox.fetch('/queues/reports')
      @report_queue.publish(device_report_id: @report.id)
    end
    if request.xhr?
      render js: "document.location = '#{report_path(@report)}'"
    else
      redirect_to report_path(@report)
    end
  end

  def destroy
    respond_to do |format|
      if @report && @report.destroy
        format.html { redirect_to reports_path, flash[:success] = 'Successfully removed report.' }
        format.js   {}
      else
        format.html { redirect_to reports_path, flash[:error] = 'Failed to remove report. Please try again.' }
        format.js   {}
      end
    end
  end

  def finished_generating
    report = current_user.reports.find_by(id: params[:report_id]) || false

    unless report == false
      report = report.is_done?
    end

    respond_to do |format|
      format.json { render :json => report.to_json }
      format.html { render :text => report.to_json }
    end
  end

  private

  def base_breadcrumbs
    add_breadcrumb "Home", "/"
    add_breadcrumb "Reports", reports_path
  end

  def get_report
    @report = current_user.reports.find_by(id: params[:id])
  end

  def show_metrics
    ops_metric_increment 'reports.show'
    ops_metric_measure 'reports.show.elapsed' do
      yield
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper

  def report_type
    case params[:action]
    when "availability"
      "Availability Report"
    when "top_alert_devices"
      "Top Alert Devices Report"
    else
      "Report Generator"
    end
  end
end

app/views/reports/_done.html.erb
<% content_for :header_javascript_block  do %>
  <script type="text/javascript">
    //TODO: Make it so that by adding this class, the export modal is included (without including the partial).
    var dataTableExportModal = new DataTableExportModal(
        {
          afterExportActionClicked: function() {},
          afterModalOpen: function() {},
          exportClass: $('.report-export'),
          exportFormat: '.csv',
          exportPath: '<%= export_report_path(@report) %>'
        }
    );

    function initDataTable(columns, table) {
      table.DataTable({
        buttons: ['csv'],
        colReorder: true,
        dom: "<'row'<'col-sm-6'B><'col-sm-6'l>>" +
             "<'row'<'col-sm-4'i><'col-sm-8'p>>" +
             "<'row'<'col-sm-12'tr>>" +
             "<'row'<'col-sm-4'i><'col-sm-8 lower'<'circle-border-spinner'>p>>",
        lengthMenu: [[ 25, 50, 100, 500 ], [ 25, 50, 100, 500 ]],
        order: [],
        pageLength: 100,
        scrollX: true,
        scrollY: false
      });
    }

    $(document).ready(function() {
      if( $(".pie-chart").length ) {
        $(".pie-chart").highcharts(<%= @report.pie_chart.to_json.html_safe %>);
      }

      if( $(".trend-chart").length ) {
        $(".trend-chart").highcharts(<%= @report.trend_chart.to_json.html_safe %>);
      }
    });
  </script>
<% end %>

<div class="row">
  <% if @report.pie_chart.present? %>
    <div class="col-lg-4">
      <div class="ibox float">
        <div class="ibox-title">
          <h5><%= t(".Average #{@report.title}") %></h5>
        </div>
        <div class="ibox-content nopadding updates pre-charts pie-chart" style="height: 350px;">
          <div class="loading-chart">
            <h4>Loading Analytics</h4>
            <%= image_tag asset_path("ajax-loader-charts.gif") %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <% if @report.trend_chart.present? %>
    <div class="<%= @report.pie_chart.present? ? 'col-lg-8' : 'col-lg-12' %>">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t(".#{@report.title} Over Time") %></h5>
        </div>
        <div class="ibox-content nopadding updates pre-charts trend-chart" style="height: 350px;">
          <div class="loading-chart">
            <h4>Loading Analytics</h4>
            <%= image_tag asset_path("ajax-loader-charts.gif") %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox">
      <div class="ibox-content nopadding overflow-auto">
        <%= hidden_field_tag 'report_id', @report.id %>
        <%=
            content_tag(
                :table,
                class: 'dataTable display compact table table-striped table-bordered table-hover reports-export',
                id: 'report-table'
            ) do
        %>
          <thead>
            <tr>
              <th name="mac"><%= t(:mac) %></th>
              <th name="host"><%= t(:primary_ip) %></th>
              <th name="category">Category</th>
              <th name="model">Model</th>
              <th name="organization">Organization</th>
              <th name="site">Site</th>
              <th name="deployment">Deployment</th>
              <th name="last_activity">Last Activity</th>
              <%= render "stats_headers", stats_headers: @report.stats_headers %>
              </tr>
          </thead>
          <tbody>
            <% @report.table.each do |mac, host, category, model, organization, _,
                                      site, deployment, last_activity, stats_details| %>
              <tr>
                <td><%= mac %></td>
                <td><%= host %></td>
                <td><%= category %></td>
                <td><%= model %></td>
                <td><%= organization %></td>
                <td><%= site %></td>
                <td><%= deployment %></td>
                <td><%= timestamp_in_users_timezone(last_activity) %></td>
                <%= render(
                  "stats_details",
                  stats_headers: @report.stats_headers,
                  stats_details: stats_details
                ) %>
              </tr>
            <% end %>
          </tbody>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render partial: 'shared/export_modal' %>

app/views/reports/_generating.html.erb
<% content_for :header_javascript_block  do %>
  <script type="text/javascript">

    function finishedGenerating() {
      $.ajax({
        type: "GET",
        url: "/reports/finished_generating.json",
        data: { report_id: "<%= @report.id %>" },
        contentType: "application/json; charset=UTF-8",
        dataType: "json",
        success: function (response) {
          if (response == true) {
            location.reload(true);
          }
        }
      });
    }

    $(document).ready(function(){
      window.setInterval(function(){
        finishedGenerating();
      }, 5000);
    });
  </script>
<% end %>

<div class="row">
  <div class="col-lg-12">
    <div class="ibox">
      <div class="ibox-title">
        <h5><%= @report.title %> Report</h5>
      </div>
      <div class="ibox-content">
        <div class="text-center">
          <h4>Generating Report</h4>
          <%= image_tag asset_path("ajax-loader-charts.gif") %>
          <div class="p-sm">
            <p>This may take a few moments.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/_stats_details.html.erb
<% if stats_headers.present? %>
  <% stats_headers.keys.each do |key| %>
    <td><%= stats_details[key] %></td>
  <% end %>
<% end %>

app/views/reports/_stats_headers.html.erb
<% if stats_headers.present? %>
  <% stats_headers.each do |name, text| %>
    <th name="<%= name %>"><%= text %></th>
  <% end %>
<% end %>

app/views/reports/destroy.js.erb
$('#report-table').DataTable().ajax.reload();

var alert = "<%= j alert_success message: t('reports.destroyed', name: @report.id) %>";
$('div.wrapper-content').prepend(alert);
setAlertExpiration($('div.wrapper-content > .alert'));

app/views/reports/index.html.erb
<% content_for :header_javascript_block  do %>
  <script type="text/javascript">
    function initDataTable(columns, table) {
      table.DataTable({
        ajax: {
          'data': function ( data ) { formatData(columns, data, table); },
          'url': '<%= "#{reports_path(format: :json)}".html_safe %>'
        },
        colReorder: true,
        columns: getColumnSettings(columns),
        dom: "<'row'<'col-sm-4'i><'col-sm-8'p>>" +
             "<'row'<'col-sm-12'tr>>" +
             "<'row'<'col-sm-4'i><'col-sm-8 lower'<'circle-border-spinner'>p>>",
        lengthMenu: [[ 25, 50, 100, 500 ], [ 25, 50, 100, 500 ]],
        pageLength: 100,
        scrollX: true,
        scrollY: false,
        serverSide: true,
        paging: false
      });
    }
  </script>
<% end %>

<%= render 'shared/page_header', locals: { title: 'report history' } %>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t(".#{@presenter.title}") %></h5>
        </div>
        <div class="ibox-content">
          <%=
            content_tag(
              :table,
              class: 'dataTable display compact table table-striped table-bordered table-hover',
              id: 'report-table',
              data: { klass: @presenter.klass }
            ) do
          %>
            <thead>
              <tr>
                <%= render 'shared/table_labels' %>
              </tr>
            </thead>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<%= render 'shared/page_header', locals: { title: 'new report' } %>

<div class="wrapper wrapper-content">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox">
        <div class="ibox-title">
          <h5><%= t(".#{@presenter.title}") %></h5>
        </div>
        <div class="ibox-content">
          <%= form_for :report, html: {class: 'form-horizontal'}, url: reports_path do |f| %>
            <%= f.hidden_field :report_type, value: @report.report_type  %>

            <div class="form-group">
              <%= f.label :organization_id, 'Organization', :class => 'control-label col-lg-2' %>
              <div class="col-lg-4">
                <%=
                    f.select :organization_id,
                             options_for_select(organizations_select_list, current_user.filter_organization),
                             {},
                             { :class => 'form-control select2' }
                %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-lg-2"></div>
              <div class="col-lg-4">
                <div class="i-checks">
                  <label>
                    <div class="icheckbox_square-green">
                      <%= f.check_box :include_hierarchy, class: 'toggle-vis' %>
                    </div>
                    Include Sub-Organizations
                  </label>
                </div>
              </div>
            </div>

            <% if @presenter.title == :vig_form %>
              <%= f.fields_for :categories do |category_fields| %>
                <% @presenter.device_categories.each do |category| %>
                  <%= category_fields.hidden_field category.id, value: category.id %>
                <% end %>
              <% end %>

              <%= f.fields_for :models do |model_fields| %>
                <% @presenter.device_models.each do |model| %>
                  <%= model_fields.hidden_field model.id, value: model.id %>
                <% end %>
              <% end %>
            <% end %>

            <% if @presenter.has_device_category_selection? %>
              <div class="form-group">
                <%= f.label :device_categories, 'Device Categories', :class => 'control-label col-lg-2' %>
                <div class="col-lg-4">
                  <%=
                      f.select :categories,
                               options_for_select(@presenter.device_categories_for_select),
                               {},
                               { multiple: true, class: 'multiselect-dropdown form-control', id: 'category-multiselect' }
                  %>
                </div>
              </div>
            <% end %>

            <% if @presenter.has_device_model_selection? %>
              <div class="form-group">
                <%= f.label :device_models, 'Device Models', :class => 'control-label col-lg-2' %>
                <div class="col-lg-4">
                  <%=
                      f.select :models,
                               grouped_options_for_select(@presenter.device_models_for_select),
                               {},
                               { multiple: true, class: 'multiselect-dropdown form-control', id: 'model-multiselect' }
                  %>
                </div>
              </div>
            <% end %>

            <div class="form-group">
              <%= f.label :deployment, 'Deployment', :class => 'control-label col-lg-2' %>
              <div class="col-lg-2">
                <%=
                    f.select :deployment,
                             options_for_select([['All', 0], ['Deployed', 1], ['Undeployed', 2]], 1),
                             {},
                             { :class => 'form-control select2-without-search' }
                %>
              </div>
            </div>

            <% if @presenter.has_time_span_selection? %>
              <div class="form-group">
                <%= f.label :range, 'Time Span', :class => 'control-label col-lg-2' %>
                <div class="col-lg-2">
                  <%=
                      f.select :range,
                               options_for_select(@presenter.ranges),
                               {},
                               { :class => 'form-control select2-without-search' } %>
                </div>
              </div>
            <% end %>

            <div class="hr-line-dashed"></div>

            <div class="form-group">
              <div class='col-lg-4 col-lg-offset-2'>
                <% if @presenter.report_count(current_user) >= DeviceReport::REPORT_LIMIT %>
                  <%=
                      f.submit 'Create',
                               :class => 'btn btn-primary',
                               :id => 'form-submit',
                               data: { :confirm => t('reports.confirm_create', report_limit: DeviceReport::REPORT_LIMIT ) }
                  %>
                <% else %>
                  <%=
                      f.submit 'Create',
                               :class => 'btn btn-primary',
                               :id => 'form-submit' %>
                <% end %>
                <%= link_to 'Cancel', reports_path, :class => 'btn' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<%= render 'shared/page_header', locals: { title: "#{@report.title} Report ##{@report.id}", skip_translate: true } %>

<div class="wrapper wrapper-content">
  <%= render @report.is_done? ? "done" : "generating" %>
</div>